remote_theme: Stravaig-Projects/stravaig-theme
plugins:
  - jekyll-remote-theme 
  - jekyll-relative-links

exclude:
  - scripts

# UPDATE ME IN A NEW REPOSITORY
title: Stravaig Clock
description: An injectable and testable clock.

kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true

# UPDATE ME IN A NEW REPOSITORY
github:
  repository_url: https://github.com/Stravaig-Projects/Stravaig.Clock

# UPDATE ME IN A NEW REPOSITORY
nuget:
  urls:
    - https://www.nuget.org/packages/Stravaig.Clock
    - https://www.nuget.org/packages/Stravaig.Clock.Testing
    - https://www.nuget.org/packages/Stravaig.Clock.DependencyInjection